import type { AllergenL10n } from "@/content-schema/l10n";

/** zh allergen-program overlays, keyed by allergen id (regenerated by `npm run gen:zh-index`). */
export const ZH_ALLERGENS: Record<string, AllergenL10n> = {};
