import type { AllergenL10n } from "@/content-schema/l10n";
import egg from "./egg";
import fish from "./fish";
import milk from "./milk";
import peanut from "./peanut";
import sesame from "./sesame";
import shellfish from "./shellfish";
import soy from "./soy";
import treeNut from "./tree-nut";
import wheat from "./wheat";

/** zh allergen-program overlays, keyed by allergen id (regenerated by `npm run gen:zh-index`). */
export const ZH_ALLERGENS: Record<string, AllergenL10n> = {
  [egg.id]: egg,
  [fish.id]: fish,
  [milk.id]: milk,
  [peanut.id]: peanut,
  [sesame.id]: sesame,
  [shellfish.id]: shellfish,
  [soy.id]: soy,
  [treeNut.id]: treeNut,
  [wheat.id]: wheat,
};
