import type { GuideL10n } from "@/content-schema/l10n";
import allergens101 from "./allergens-101";
import howFast from "./how-fast";
import milkAndSolids from "./milk-and-solids";
import ordering from "./ordering";
import whenToStart from "./when-to-start";
import whySolids from "./why-solids";

/** zh guide overlays, keyed by slug (regenerated by `npm run gen:zh-index`). */
export const ZH_GUIDES: Record<string, GuideL10n> = {
  [allergens101.slug]: allergens101,
  [howFast.slug]: howFast,
  [milkAndSolids.slug]: milkAndSolids,
  [ordering.slug]: ordering,
  [whenToStart.slug]: whenToStart,
  [whySolids.slug]: whySolids,
};
