import type { FamilyRecipeL10n } from "@/content-schema/l10n";
import bananaOatPancakes from "./banana-oat-pancakes";
import beefBroccoliStirFry from "./beef-broccoli-stir-fry";
import chickenCornSoup from "./chicken-corn-soup";
import eggFriedRice from "./egg-fried-rice";
import honeySoySalmonRiceBowl from "./honey-soy-salmon-rice-bowl";
import porkCabbageDumplings from "./pork-cabbage-dumplings";
import seaweedEggDropSoup from "./seaweed-egg-drop-soup";
import steamedEggCustard from "./steamed-egg-custard";
import tomatoBeefNoodleSoup from "./tomato-beef-noodle-soup";
import tomatoEggStirFry from "./tomato-egg-stir-fry";

/** zh family-recipe overlays, keyed by slug (regenerated by `npm run gen:zh-index`). */
export const ZH_FAMILY_RECIPES: Record<string, FamilyRecipeL10n> = {
  [bananaOatPancakes.slug]: bananaOatPancakes,
  [beefBroccoliStirFry.slug]: beefBroccoliStirFry,
  [chickenCornSoup.slug]: chickenCornSoup,
  [eggFriedRice.slug]: eggFriedRice,
  [honeySoySalmonRiceBowl.slug]: honeySoySalmonRiceBowl,
  [porkCabbageDumplings.slug]: porkCabbageDumplings,
  [seaweedEggDropSoup.slug]: seaweedEggDropSoup,
  [steamedEggCustard.slug]: steamedEggCustard,
  [tomatoBeefNoodleSoup.slug]: tomatoBeefNoodleSoup,
  [tomatoEggStirFry.slug]: tomatoEggStirFry,
};
