import type { ChinesePoem } from "@/content-schema/read-aloud";

/**
 * GENERATED by scripts/gen-read-aloud-rhymes.mjs — do not hand-edit;
 * regenerate instead. 蒙学顺口溜: rhythmic recitation classics (三字经,
 * 百家姓, 千字文, 声律启蒙) from the public-domain chinese-poetry corpus,
 * converted to simplified characters. Pinyin is machine-generated
 * (pinyin-pro); fix a rare heteronym by moving the piece into the curated
 * chinese.ts, not by editing this file.
 */
export const chineseRhymesGenerated: ChinesePoem[] = [
  {
    "slug": "san-zi-jing-1",
    "title": "三字经 · 其一",
    "pinyinTitle": "sān zì jīng · qí yī",
    "author": "王应麟（传）",
    "dynasty": "宋",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "人之初，",
        "pinyin": "rén zhī chū,"
      },
      {
        "hanzi": "性本善，",
        "pinyin": "xìng běn shàn,"
      },
      {
        "hanzi": "性相近，",
        "pinyin": "xìng xiāng jìn,"
      },
      {
        "hanzi": "习相远。",
        "pinyin": "xí xiāng yuǎn."
      },
      {
        "hanzi": "茍不教，",
        "pinyin": "jì bú jiào,"
      },
      {
        "hanzi": "性乃迁，",
        "pinyin": "xìng nǎi qiān,"
      },
      {
        "hanzi": "教之道，",
        "pinyin": "jiào zhī dào,"
      },
      {
        "hanzi": "贵以专。",
        "pinyin": "guì yǐ zhuān."
      },
      {
        "hanzi": "昔孟母，",
        "pinyin": "xī mèng mǔ,"
      },
      {
        "hanzi": "择邻处，",
        "pinyin": "zé lín chù,"
      },
      {
        "hanzi": "子不学，",
        "pinyin": "zǐ bù xué,"
      },
      {
        "hanzi": "断机杼。",
        "pinyin": "duàn jī zhù."
      },
      {
        "hanzi": "窦燕山，",
        "pinyin": "dòu yān shān,"
      },
      {
        "hanzi": "有义方，",
        "pinyin": "yǒu yì fāng,"
      },
      {
        "hanzi": "教五子，",
        "pinyin": "jiào wǔ zǐ,"
      },
      {
        "hanzi": "名俱扬。",
        "pinyin": "míng jù yáng."
      }
    ]
  },
  {
    "slug": "san-zi-jing-2",
    "title": "三字经 · 其二",
    "pinyinTitle": "sān zì jīng · qí èr",
    "author": "王应麟（传）",
    "dynasty": "宋",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "养不教，",
        "pinyin": "yǎng bú jiào,"
      },
      {
        "hanzi": "父之过，",
        "pinyin": "fù zhī guò,"
      },
      {
        "hanzi": "教不严，",
        "pinyin": "jiào bù yán,"
      },
      {
        "hanzi": "师之惰。",
        "pinyin": "shī zhī duò."
      },
      {
        "hanzi": "子不学，",
        "pinyin": "zǐ bù xué,"
      },
      {
        "hanzi": "非所宜，",
        "pinyin": "fēi suǒ yí,"
      },
      {
        "hanzi": "幼不学，",
        "pinyin": "yòu bù xué,"
      },
      {
        "hanzi": "老何为？",
        "pinyin": "lǎo hé wèi?"
      },
      {
        "hanzi": "玉不琢，",
        "pinyin": "yù bù zhuó,"
      },
      {
        "hanzi": "不成器，",
        "pinyin": "bù chéng qì,"
      },
      {
        "hanzi": "人不学，",
        "pinyin": "rén bù xué,"
      },
      {
        "hanzi": "不知义。",
        "pinyin": "bù zhī yì."
      },
      {
        "hanzi": "为人子，",
        "pinyin": "wèi rén zǐ,"
      },
      {
        "hanzi": "方少时，",
        "pinyin": "fāng shǎo shí,"
      },
      {
        "hanzi": "亲师友，",
        "pinyin": "qīn shī yǒu,"
      },
      {
        "hanzi": "习礼仪。",
        "pinyin": "xí lǐ yí."
      }
    ]
  },
  {
    "slug": "san-zi-jing-3",
    "title": "三字经 · 其三",
    "pinyinTitle": "sān zì jīng · qí sān",
    "author": "王应麟（传）",
    "dynasty": "宋",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "香九龄，",
        "pinyin": "xiāng jiǔ líng,"
      },
      {
        "hanzi": "能温席，",
        "pinyin": "néng wēn xí,"
      },
      {
        "hanzi": "孝于亲，",
        "pinyin": "xiào yú qīn,"
      },
      {
        "hanzi": "所当执。",
        "pinyin": "suǒ dāng zhí."
      },
      {
        "hanzi": "融四岁，",
        "pinyin": "róng sì suì,"
      },
      {
        "hanzi": "能让梨，",
        "pinyin": "néng ràng lí,"
      },
      {
        "hanzi": "弟于长，",
        "pinyin": "dì yú cháng,"
      },
      {
        "hanzi": "宜先知。",
        "pinyin": "yí xiān zhī."
      },
      {
        "hanzi": "首孝弟，",
        "pinyin": "shǒu xiào dì,"
      },
      {
        "hanzi": "次见闻，",
        "pinyin": "cì jiàn wén,"
      },
      {
        "hanzi": "知某数，",
        "pinyin": "zhī mǒu shù,"
      },
      {
        "hanzi": "识某文。",
        "pinyin": "shí mǒu wén."
      },
      {
        "hanzi": "一而十，",
        "pinyin": "yī ér shí,"
      },
      {
        "hanzi": "十而百，",
        "pinyin": "shí ér bǎi,"
      },
      {
        "hanzi": "百而千，",
        "pinyin": "bǎi ér qiān,"
      },
      {
        "hanzi": "千而万。",
        "pinyin": "qiān ér wàn."
      }
    ]
  },
  {
    "slug": "san-zi-jing-4",
    "title": "三字经 · 其四",
    "pinyinTitle": "sān zì jīng · qí sì",
    "author": "王应麟（传）",
    "dynasty": "宋",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "三才者，",
        "pinyin": "sān cái zhě,"
      },
      {
        "hanzi": "天地人，",
        "pinyin": "tiān dì rén,"
      },
      {
        "hanzi": "三光者，",
        "pinyin": "sān guāng zhě,"
      },
      {
        "hanzi": "日月星。",
        "pinyin": "rì yuè xīng."
      },
      {
        "hanzi": "三纲者，",
        "pinyin": "sān gāng zhě,"
      },
      {
        "hanzi": "君臣义，",
        "pinyin": "jūn chén yì,"
      },
      {
        "hanzi": "父子亲，",
        "pinyin": "fù zǐ qīn,"
      },
      {
        "hanzi": "夫妇顺。",
        "pinyin": "fū fù shùn."
      },
      {
        "hanzi": "曰春夏，",
        "pinyin": "yuē chūn xià,"
      },
      {
        "hanzi": "曰秋冬，",
        "pinyin": "yuē qiū dōng,"
      },
      {
        "hanzi": "此四时，",
        "pinyin": "cǐ sì shí,"
      },
      {
        "hanzi": "运不穷。",
        "pinyin": "yùn bù qióng."
      },
      {
        "hanzi": "曰南北，",
        "pinyin": "yuē nán běi,"
      },
      {
        "hanzi": "曰西东，",
        "pinyin": "yuē xī dōng,"
      },
      {
        "hanzi": "此四方，",
        "pinyin": "cǐ sì fāng,"
      },
      {
        "hanzi": "应乎中。",
        "pinyin": "yìng hū zhōng."
      }
    ]
  },
  {
    "slug": "san-zi-jing-5",
    "title": "三字经 · 其五",
    "pinyinTitle": "sān zì jīng · qí wǔ",
    "author": "王应麟（传）",
    "dynasty": "宋",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "曰水火，",
        "pinyin": "yuē shuǐ huǒ,"
      },
      {
        "hanzi": "木金土，",
        "pinyin": "mù jīn tǔ,"
      },
      {
        "hanzi": "此五行，",
        "pinyin": "cǐ wǔ háng,"
      },
      {
        "hanzi": "本乎数。",
        "pinyin": "běn hū shù."
      },
      {
        "hanzi": "十干者，",
        "pinyin": "shí gān zhě,"
      },
      {
        "hanzi": "甲至癸，",
        "pinyin": "jiǎ zhì guǐ,"
      },
      {
        "hanzi": "十二支，",
        "pinyin": "shí èr zhī,"
      },
      {
        "hanzi": "子至亥。",
        "pinyin": "zǐ zhì hài."
      },
      {
        "hanzi": "曰黄道，",
        "pinyin": "yuē huáng dào,"
      },
      {
        "hanzi": "日所躔，",
        "pinyin": "rì suǒ chán,"
      },
      {
        "hanzi": "曰赤道，",
        "pinyin": "yuē chì dào,"
      },
      {
        "hanzi": "当中权。",
        "pinyin": "dāng zhōng quán."
      },
      {
        "hanzi": "赤道下，",
        "pinyin": "chì dào xià,"
      },
      {
        "hanzi": "温暖极，",
        "pinyin": "wēn nuǎn jí,"
      },
      {
        "hanzi": "我中华，",
        "pinyin": "wǒ zhōng huá,"
      },
      {
        "hanzi": "在东北。",
        "pinyin": "zài dōng běi."
      }
    ]
  },
  {
    "slug": "san-zi-jing-6",
    "title": "三字经 · 其六",
    "pinyinTitle": "sān zì jīng · qí liù",
    "author": "王应麟（传）",
    "dynasty": "宋",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "寒燠均，",
        "pinyin": "hán yù jūn,"
      },
      {
        "hanzi": "霜露改，",
        "pinyin": "shuāng lù gǎi,"
      },
      {
        "hanzi": "右高原，",
        "pinyin": "yòu gāo yuán,"
      },
      {
        "hanzi": "左大海。",
        "pinyin": "zuǒ dà hǎi."
      },
      {
        "hanzi": "曰江河，",
        "pinyin": "yuē jiāng hé,"
      },
      {
        "hanzi": "曰淮济，",
        "pinyin": "yuē huái jì,"
      },
      {
        "hanzi": "此四渎，",
        "pinyin": "cǐ sì dú,"
      },
      {
        "hanzi": "水之纪。",
        "pinyin": "shuǐ zhī jì."
      },
      {
        "hanzi": "曰岱华，",
        "pinyin": "yuē dài huá,"
      },
      {
        "hanzi": "嵩恒衡，",
        "pinyin": "sōng héng héng,"
      },
      {
        "hanzi": "此五岳，",
        "pinyin": "cǐ wǔ yuè,"
      },
      {
        "hanzi": "山之名。",
        "pinyin": "shān zhī míng."
      },
      {
        "hanzi": "古九州，",
        "pinyin": "gǔ jiǔ zhōu,"
      },
      {
        "hanzi": "今改制，",
        "pinyin": "jīn gǎi zhì,"
      },
      {
        "hanzi": "称行省，",
        "pinyin": "chēng xíng shěng,"
      },
      {
        "hanzi": "三十五。",
        "pinyin": "sān shí wǔ."
      }
    ]
  },
  {
    "slug": "san-zi-jing-7",
    "title": "三字经 · 其七",
    "pinyinTitle": "sān zì jīng · qí qī",
    "author": "王应麟（传）",
    "dynasty": "宋",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "曰士农，",
        "pinyin": "yuē shì nóng,"
      },
      {
        "hanzi": "曰工商，",
        "pinyin": "yuē gōng shāng,"
      },
      {
        "hanzi": "此四民，",
        "pinyin": "cǐ sì mín,"
      },
      {
        "hanzi": "国之良。",
        "pinyin": "guó zhī liáng."
      },
      {
        "hanzi": "地所生，",
        "pinyin": "dì suǒ shēng,"
      },
      {
        "hanzi": "有草木，",
        "pinyin": "yǒu cǎo mù,"
      },
      {
        "hanzi": "此植物，",
        "pinyin": "cǐ zhí wù,"
      },
      {
        "hanzi": "遍水陆。",
        "pinyin": "biàn shuǐ lù."
      },
      {
        "hanzi": "有虫鱼，",
        "pinyin": "yǒu chóng yú,"
      },
      {
        "hanzi": "有鸟兽，",
        "pinyin": "yǒu niǎo shòu,"
      },
      {
        "hanzi": "此动物，",
        "pinyin": "cǐ dòng wù,"
      },
      {
        "hanzi": "能飞走。",
        "pinyin": "néng fēi zǒu."
      },
      {
        "hanzi": "稻粱菽，",
        "pinyin": "dào liáng shū,"
      },
      {
        "hanzi": "麦黍稷，",
        "pinyin": "mài shǔ jì,"
      },
      {
        "hanzi": "此六谷，",
        "pinyin": "cǐ liù gǔ,"
      },
      {
        "hanzi": "人所食。",
        "pinyin": "rén suǒ shí."
      }
    ]
  },
  {
    "slug": "san-zi-jing-8",
    "title": "三字经 · 其八",
    "pinyinTitle": "sān zì jīng · qí bā",
    "author": "王应麟（传）",
    "dynasty": "宋",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "马牛羊，",
        "pinyin": "mǎ niú yáng,"
      },
      {
        "hanzi": "鸡犬豕，",
        "pinyin": "jī quǎn shǐ,"
      },
      {
        "hanzi": "此六畜，",
        "pinyin": "cǐ liù chù,"
      },
      {
        "hanzi": "人所饲。",
        "pinyin": "rén suǒ sì."
      },
      {
        "hanzi": "曰喜怒，",
        "pinyin": "yuē xǐ nù,"
      },
      {
        "hanzi": "曰哀惧，",
        "pinyin": "yuē āi jù,"
      },
      {
        "hanzi": "爱恶欲，",
        "pinyin": "ài è yù,"
      },
      {
        "hanzi": "七情具。",
        "pinyin": "qī qíng jù."
      },
      {
        "hanzi": "曰仁义，",
        "pinyin": "yuē rén yì,"
      },
      {
        "hanzi": "礼智信，",
        "pinyin": "lǐ zhì xìn,"
      },
      {
        "hanzi": "此五常，",
        "pinyin": "cǐ wǔ cháng,"
      },
      {
        "hanzi": "不容紊。",
        "pinyin": "bù róng wěn."
      },
      {
        "hanzi": "青赤黄，",
        "pinyin": "qīng chì huáng,"
      },
      {
        "hanzi": "及白黑，",
        "pinyin": "jí bái hēi,"
      },
      {
        "hanzi": "此五色，",
        "pinyin": "cǐ wǔ sè,"
      },
      {
        "hanzi": "目所识。",
        "pinyin": "mù suǒ shí."
      }
    ]
  },
  {
    "slug": "bai-jia-xing-1",
    "title": "百家姓 · 其一",
    "pinyinTitle": "bǎi jiā xìng · qí yī",
    "author": "佚名",
    "dynasty": "北宋",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "赵钱孙李，",
        "pinyin": "zhào qián sūn lǐ,"
      },
      {
        "hanzi": "周吴郑王。",
        "pinyin": "zhōu wú zhèng wáng."
      },
      {
        "hanzi": "冯陈褚卫，",
        "pinyin": "féng chén chǔ wèi,"
      },
      {
        "hanzi": "蒋沈韩杨。",
        "pinyin": "jiǎng shěn hán yáng."
      },
      {
        "hanzi": "朱秦尤许，",
        "pinyin": "zhū qín yóu xǔ,"
      },
      {
        "hanzi": "何吕施张。",
        "pinyin": "hé lǚ shī zhāng."
      },
      {
        "hanzi": "孔曹严华，",
        "pinyin": "kǒng cáo yán huá,"
      },
      {
        "hanzi": "金魏陶姜。",
        "pinyin": "jīn wèi táo jiāng."
      },
      {
        "hanzi": "戚谢邹喻，",
        "pinyin": "qī xiè zōu yù,"
      },
      {
        "hanzi": "柏水窦章。",
        "pinyin": "bǎi shuǐ dòu zhāng."
      },
      {
        "hanzi": "云苏潘葛，",
        "pinyin": "yún sū pān gě,"
      },
      {
        "hanzi": "奚范彭郎。",
        "pinyin": "xī fàn péng láng."
      },
      {
        "hanzi": "鲁韦昌马，",
        "pinyin": "lǔ wéi chāng mǎ,"
      },
      {
        "hanzi": "苗凤花方。",
        "pinyin": "miáo fèng huā fāng."
      },
      {
        "hanzi": "俞任袁柳，",
        "pinyin": "yú rèn yuán liǔ,"
      },
      {
        "hanzi": "酆鲍史唐。",
        "pinyin": "fēng bào shǐ táng."
      }
    ]
  },
  {
    "slug": "bai-jia-xing-2",
    "title": "百家姓 · 其二",
    "pinyinTitle": "bǎi jiā xìng · qí èr",
    "author": "佚名",
    "dynasty": "北宋",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "费廉岑薛，",
        "pinyin": "fèi lián cén xuē,"
      },
      {
        "hanzi": "雷贺倪汤。",
        "pinyin": "léi hè ní tāng."
      },
      {
        "hanzi": "滕殷罗毕，",
        "pinyin": "téng yīn luó bì,"
      },
      {
        "hanzi": "郝邬安常。",
        "pinyin": "hǎo wū ān cháng."
      },
      {
        "hanzi": "乐于时傅，",
        "pinyin": "lè yú shí fù,"
      },
      {
        "hanzi": "皮卞齐康。",
        "pinyin": "pí biàn qí kāng."
      },
      {
        "hanzi": "伍余元卜，",
        "pinyin": "wǔ yú yuán bǔ,"
      },
      {
        "hanzi": "顾孟平黄。",
        "pinyin": "gù mèng píng huáng."
      },
      {
        "hanzi": "和穆萧尹，",
        "pinyin": "hé mù xiāo yǐn,"
      },
      {
        "hanzi": "姚邵湛汪。",
        "pinyin": "yáo shào zhàn wāng."
      },
      {
        "hanzi": "祁毛禹狄，",
        "pinyin": "qí máo yǔ dí,"
      },
      {
        "hanzi": "米贝明臧。",
        "pinyin": "mǐ bèi míng zāng."
      },
      {
        "hanzi": "计伏成戴，",
        "pinyin": "jì fú chéng dài,"
      },
      {
        "hanzi": "谈宋茅庞。",
        "pinyin": "tán sòng máo páng."
      },
      {
        "hanzi": "熊纪舒屈，",
        "pinyin": "xióng jì shū qū,"
      },
      {
        "hanzi": "项祝董梁。",
        "pinyin": "xiàng zhù dǒng liáng."
      }
    ]
  },
  {
    "slug": "qian-zi-wen-1",
    "title": "千字文 · 其一",
    "pinyinTitle": "qiān zì wén · qí yī",
    "author": "周兴嗣",
    "dynasty": "南朝·梁",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "天地玄黄",
        "pinyin": "tiān dì xuán huáng"
      },
      {
        "hanzi": "宇宙洪荒",
        "pinyin": "yǔ zhòu hóng huāng"
      },
      {
        "hanzi": "日月盈昃",
        "pinyin": "rì yuè yíng zè"
      },
      {
        "hanzi": "辰宿列张",
        "pinyin": "chén sù liè zhāng"
      },
      {
        "hanzi": "寒来暑往",
        "pinyin": "hán lái shǔ wǎng"
      },
      {
        "hanzi": "秋收冬藏",
        "pinyin": "qiū shōu dōng cáng"
      },
      {
        "hanzi": "闰余成岁",
        "pinyin": "rùn yú chéng suì"
      },
      {
        "hanzi": "律吕调阳",
        "pinyin": "lǜ lǚ tiáo yáng"
      },
      {
        "hanzi": "云腾致雨",
        "pinyin": "yún téng zhì yǔ"
      },
      {
        "hanzi": "露结为霜",
        "pinyin": "lù jié wèi shuāng"
      },
      {
        "hanzi": "金生丽水",
        "pinyin": "jīn shēng lí shuǐ"
      },
      {
        "hanzi": "玉出崐冈",
        "pinyin": "yù chū kūn gāng"
      },
      {
        "hanzi": "剑号巨阙",
        "pinyin": "jiàn hào jù quē"
      },
      {
        "hanzi": "珠称夜光",
        "pinyin": "zhū chēng yè guāng"
      },
      {
        "hanzi": "果珍李柰",
        "pinyin": "guǒ zhēn lǐ nài"
      },
      {
        "hanzi": "菜重芥姜",
        "pinyin": "cài zhòng jiè jiāng"
      }
    ]
  },
  {
    "slug": "qian-zi-wen-2",
    "title": "千字文 · 其二",
    "pinyinTitle": "qiān zì wén · qí èr",
    "author": "周兴嗣",
    "dynasty": "南朝·梁",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "海咸河淡",
        "pinyin": "hǎi xián hé dàn"
      },
      {
        "hanzi": "鳞潜羽翔",
        "pinyin": "lín qián yǔ xiáng"
      },
      {
        "hanzi": "龙师火帝",
        "pinyin": "lóng shī huǒ dì"
      },
      {
        "hanzi": "鸟官人皇",
        "pinyin": "niǎo guān rén huáng"
      },
      {
        "hanzi": "始制文字",
        "pinyin": "shǐ zhì wén zì"
      },
      {
        "hanzi": "乃服衣裳",
        "pinyin": "nǎi fú yī shang"
      },
      {
        "hanzi": "推位让国",
        "pinyin": "tuī wèi ràng guó"
      },
      {
        "hanzi": "有虞陶唐",
        "pinyin": "yǒu yú táo táng"
      },
      {
        "hanzi": "吊民伐罪",
        "pinyin": "diào mín fá zuì"
      },
      {
        "hanzi": "周发殷汤",
        "pinyin": "zhōu fā yīn tāng"
      },
      {
        "hanzi": "坐朝问道",
        "pinyin": "zuò cháo wèn dào"
      },
      {
        "hanzi": "垂拱平章",
        "pinyin": "chuí gǒng píng zhāng"
      },
      {
        "hanzi": "爱育黎首",
        "pinyin": "ài yù lí shǒu"
      },
      {
        "hanzi": "臣伏戎羌",
        "pinyin": "chén fú róng qiāng"
      },
      {
        "hanzi": "遐迩壹体",
        "pinyin": "xiá ěr yī tǐ"
      },
      {
        "hanzi": "率宾归王",
        "pinyin": "lǜ bīn guī wáng"
      }
    ]
  },
  {
    "slug": "qian-zi-wen-3",
    "title": "千字文 · 其三",
    "pinyinTitle": "qiān zì wén · qí sān",
    "author": "周兴嗣",
    "dynasty": "南朝·梁",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "鸣凤在树",
        "pinyin": "míng fèng zài shù"
      },
      {
        "hanzi": "白驹食场",
        "pinyin": "bái jū shí chǎng"
      },
      {
        "hanzi": "化被草木",
        "pinyin": "huà bèi cǎo mù"
      },
      {
        "hanzi": "赖及万方",
        "pinyin": "lài jí wàn fāng"
      },
      {
        "hanzi": "盖此身发",
        "pinyin": "gài cǐ shēn fā"
      },
      {
        "hanzi": "四大五常",
        "pinyin": "sì dà wǔ cháng"
      },
      {
        "hanzi": "恭惟鞠养",
        "pinyin": "gōng wéi jū yǎng"
      },
      {
        "hanzi": "岂敢毁伤",
        "pinyin": "qǐ gǎn huǐ shāng"
      },
      {
        "hanzi": "女慕贞絜",
        "pinyin": "nǚ mù zhēn jié"
      },
      {
        "hanzi": "男效才良",
        "pinyin": "nán xiào cái liáng"
      },
      {
        "hanzi": "知过必改",
        "pinyin": "zhī guò bì gǎi"
      },
      {
        "hanzi": "得能莫忘",
        "pinyin": "dé néng mò wàng"
      },
      {
        "hanzi": "罔谈彼短",
        "pinyin": "wǎng tán bǐ duǎn"
      },
      {
        "hanzi": "靡恃己长",
        "pinyin": "mí shì jǐ cháng"
      },
      {
        "hanzi": "信使可覆",
        "pinyin": "xìn shǐ kě fù"
      },
      {
        "hanzi": "器欲难量",
        "pinyin": "qì yù nán liáng"
      }
    ]
  },
  {
    "slug": "qian-zi-wen-4",
    "title": "千字文 · 其四",
    "pinyinTitle": "qiān zì wén · qí sì",
    "author": "周兴嗣",
    "dynasty": "南朝·梁",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "墨悲丝染",
        "pinyin": "mò bēi sī rǎn"
      },
      {
        "hanzi": "诗赞羔羊",
        "pinyin": "shī zàn gāo yáng"
      },
      {
        "hanzi": "景行维贤",
        "pinyin": "jǐng xíng wéi xián"
      },
      {
        "hanzi": "克念作圣",
        "pinyin": "kè niàn zuò shèng"
      },
      {
        "hanzi": "德建名立",
        "pinyin": "dé jiàn míng lì"
      },
      {
        "hanzi": "形端表正",
        "pinyin": "xíng duān biǎo zhèng"
      },
      {
        "hanzi": "空谷传声",
        "pinyin": "kōng gǔ chuán shēng"
      },
      {
        "hanzi": "虚堂习听",
        "pinyin": "xū táng xí tīng"
      },
      {
        "hanzi": "祸因恶积",
        "pinyin": "huò yīn è jī"
      },
      {
        "hanzi": "福缘善庆",
        "pinyin": "fú yuán shàn qìng"
      },
      {
        "hanzi": "尺璧非宝",
        "pinyin": "chǐ bì fēi bǎo"
      },
      {
        "hanzi": "寸阴是竞",
        "pinyin": "cùn yīn shì jìng"
      },
      {
        "hanzi": "资父事君",
        "pinyin": "zī fù shì jūn"
      },
      {
        "hanzi": "曰严与敬",
        "pinyin": "yuē yán yǔ jìng"
      },
      {
        "hanzi": "孝当竭力",
        "pinyin": "xiào dāng jié lì"
      },
      {
        "hanzi": "忠则尽命",
        "pinyin": "zhōng zé jìn mìng"
      }
    ]
  },
  {
    "slug": "qian-zi-wen-5",
    "title": "千字文 · 其五",
    "pinyinTitle": "qiān zì wén · qí wǔ",
    "author": "周兴嗣",
    "dynasty": "南朝·梁",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "临深履薄",
        "pinyin": "lín shēn lǚ bó"
      },
      {
        "hanzi": "夙兴温凊",
        "pinyin": "sù xīng wēn qìng"
      },
      {
        "hanzi": "似兰斯馨",
        "pinyin": "sì lán sī xīn"
      },
      {
        "hanzi": "如松之盛",
        "pinyin": "rú sōng zhī shèng"
      },
      {
        "hanzi": "川流不息",
        "pinyin": "chuān liú bù xī"
      },
      {
        "hanzi": "渊澄取映",
        "pinyin": "yuān chéng qǔ yìng"
      },
      {
        "hanzi": "容止若思",
        "pinyin": "róng zhǐ ruò sī"
      },
      {
        "hanzi": "言辞安定",
        "pinyin": "yán cí ān dìng"
      },
      {
        "hanzi": "笃初诚美",
        "pinyin": "dǔ chū chéng měi"
      },
      {
        "hanzi": "慎终宜令",
        "pinyin": "shèn zhōng yí lìng"
      },
      {
        "hanzi": "荣业所基",
        "pinyin": "róng yè suǒ jī"
      },
      {
        "hanzi": "籍甚无竟",
        "pinyin": "jí shèn wú jìng"
      },
      {
        "hanzi": "学优登仕",
        "pinyin": "xué yōu dēng shì"
      },
      {
        "hanzi": "摄职从政",
        "pinyin": "shè zhí cóng zhèng"
      },
      {
        "hanzi": "存以甘棠",
        "pinyin": "cún yǐ gān táng"
      },
      {
        "hanzi": "去而益咏",
        "pinyin": "qù ér yì yǒng"
      }
    ]
  },
  {
    "slug": "qian-zi-wen-6",
    "title": "千字文 · 其六",
    "pinyinTitle": "qiān zì wén · qí liù",
    "author": "周兴嗣",
    "dynasty": "南朝·梁",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "乐殊贵贱",
        "pinyin": "lè shū guì jiàn"
      },
      {
        "hanzi": "礼别尊卑",
        "pinyin": "lǐ bié zūn bēi"
      },
      {
        "hanzi": "上和下睦",
        "pinyin": "shàng hé xià mù"
      },
      {
        "hanzi": "夫唱妇随",
        "pinyin": "fū chàng fù suí"
      },
      {
        "hanzi": "外受傅训",
        "pinyin": "wài shòu fù xùn"
      },
      {
        "hanzi": "入奉母仪",
        "pinyin": "rù fèng mǔ yí"
      },
      {
        "hanzi": "诸姑伯叔",
        "pinyin": "zhū gū bó shū"
      },
      {
        "hanzi": "犹子比儿",
        "pinyin": "yóu zǐ bǐ ér"
      },
      {
        "hanzi": "孔怀兄弟",
        "pinyin": "kǒng huái xiōng dì"
      },
      {
        "hanzi": "同气连枝",
        "pinyin": "tóng qì lián zhī"
      },
      {
        "hanzi": "交友投分",
        "pinyin": "jiāo yǒu tóu fēn"
      },
      {
        "hanzi": "切磨箴规",
        "pinyin": "qiè mó zhēn guī"
      },
      {
        "hanzi": "仁慈隐恻",
        "pinyin": "rén cí yǐn cè"
      },
      {
        "hanzi": "造次弗离",
        "pinyin": "zào cì fú lí"
      },
      {
        "hanzi": "节义廉退",
        "pinyin": "jié yì lián tuì"
      },
      {
        "hanzi": "颠沛匪亏",
        "pinyin": "diān pèi fěi kuī"
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-yi-dong-1",
    "title": "声律启蒙 · 一东 其一",
    "pinyinTitle": "shēng lǜ qǐ méng · yì dōng qí yī",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "云对雨，",
        "pinyin": "yún duì yǔ,"
      },
      {
        "hanzi": "雪对风，",
        "pinyin": "xuě duì fēng,"
      },
      {
        "hanzi": "晚照对晴空。",
        "pinyin": "wǎn zhào duì qíng kōng."
      },
      {
        "hanzi": "来鸿对去燕，",
        "pinyin": "lái hóng duì qù yàn,"
      },
      {
        "hanzi": "宿鸟对鸣虫。",
        "pinyin": "sù niǎo duì míng chóng."
      },
      {
        "hanzi": "三尺剑，",
        "pinyin": "sān chǐ jiàn,"
      },
      {
        "hanzi": "六钧弓，",
        "pinyin": "liù jūn gōng,"
      },
      {
        "hanzi": "岭北对江东。",
        "pinyin": "lǐng běi duì jiāng dōng."
      },
      {
        "hanzi": "人间清暑殿，",
        "pinyin": "rén jiān qīng shǔ diàn,"
      },
      {
        "hanzi": "天上广寒宫。",
        "pinyin": "tiān shàng guǎng hán gōng."
      },
      {
        "hanzi": "两岸晓烟杨柳绿，",
        "pinyin": "liǎng àn xiǎo yān yáng liǔ lǜ,"
      },
      {
        "hanzi": "一园春雨杏花红。",
        "pinyin": "yì yuán chūn yǔ xìng huā hóng."
      },
      {
        "hanzi": "两鬓风霜，",
        "pinyin": "liǎng bìn fēng shuāng,"
      },
      {
        "hanzi": "途次早行之客；",
        "pinyin": "tú cì zǎo xíng zhī kè;"
      },
      {
        "hanzi": "一蓑烟雨，",
        "pinyin": "yì suō yān yǔ,"
      },
      {
        "hanzi": "溪边晚钓之翁。",
        "pinyin": "xī biān wǎn diào zhī wēng."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-yi-dong-2",
    "title": "声律启蒙 · 一东 其二",
    "pinyinTitle": "shēng lǜ qǐ méng · yì dōng qí èr",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "沿对革，",
        "pinyin": "yán duì gé,"
      },
      {
        "hanzi": "异对同，",
        "pinyin": "yì duì tóng,"
      },
      {
        "hanzi": "白叟对黄童。",
        "pinyin": "bái sǒu duì huáng tóng."
      },
      {
        "hanzi": "江风对海雾，",
        "pinyin": "jiāng fēng duì hǎi wù,"
      },
      {
        "hanzi": "牧子对渔翁。",
        "pinyin": "mù zǐ duì yú wēng."
      },
      {
        "hanzi": "颜巷陋，",
        "pinyin": "yán xiàng lòu,"
      },
      {
        "hanzi": "阮途穷，",
        "pinyin": "ruǎn tú qióng,"
      },
      {
        "hanzi": "冀北对辽东。",
        "pinyin": "jì běi duì liáo dōng."
      },
      {
        "hanzi": "池中濯足水，",
        "pinyin": "chí zhōng zhuó zú shuǐ,"
      },
      {
        "hanzi": "门外打头风。",
        "pinyin": "mén wài dǎ tóu fēng."
      },
      {
        "hanzi": "梁帝讲经同泰寺，",
        "pinyin": "liáng dì jiǎng jīng tóng tài sì,"
      },
      {
        "hanzi": "汉皇置酒未央宫。",
        "pinyin": "hàn huáng zhì jiǔ wèi yāng gōng."
      },
      {
        "hanzi": "尘虑萦心，",
        "pinyin": "chén lǜ yíng xīn,"
      },
      {
        "hanzi": "懒抚七弦绿绮；",
        "pinyin": "lǎn fǔ qī xián lǜ qǐ;"
      },
      {
        "hanzi": "霜华满鬓，",
        "pinyin": "shuāng huá mǎn bìn,"
      },
      {
        "hanzi": "羞看百炼青铜。",
        "pinyin": "xiū kàn bǎi liàn qīng tóng."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-yi-dong-3",
    "title": "声律启蒙 · 一东 其三",
    "pinyinTitle": "shēng lǜ qǐ méng · yì dōng qí sān",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "贫对富，",
        "pinyin": "pín duì fù,"
      },
      {
        "hanzi": "塞对通，",
        "pinyin": "sāi duì tōng,"
      },
      {
        "hanzi": "野叟对溪童。",
        "pinyin": "yě sǒu duì xī tóng."
      },
      {
        "hanzi": "鬓皤对眉绿，",
        "pinyin": "bìn pó duì méi lǜ,"
      },
      {
        "hanzi": "齿皓对唇红。",
        "pinyin": "chǐ hào duì chún hóng."
      },
      {
        "hanzi": "天浩浩，",
        "pinyin": "tiān hào hào,"
      },
      {
        "hanzi": "日融融，",
        "pinyin": "rì róng róng,"
      },
      {
        "hanzi": "佩剑对弯弓。",
        "pinyin": "pèi jiàn duì wān gōng."
      },
      {
        "hanzi": "半溪流水绿，",
        "pinyin": "bàn xī liú shuǐ lǜ,"
      },
      {
        "hanzi": "千树落花红。",
        "pinyin": "qiān shù luò huā hóng."
      },
      {
        "hanzi": "野渡燕穿杨柳雨，",
        "pinyin": "yě dù yàn chuān yáng liǔ yǔ,"
      },
      {
        "hanzi": "芳池鱼戏芰荷风。",
        "pinyin": "fāng chí yú xì jì hé fēng."
      },
      {
        "hanzi": "女子眉纤，",
        "pinyin": "nǚ zǐ méi xiān,"
      },
      {
        "hanzi": "额下现一弯新月；",
        "pinyin": "é xià xiàn yì wān xīn yuè;"
      },
      {
        "hanzi": "男儿气壮，",
        "pinyin": "nán ér qì zhuàng,"
      },
      {
        "hanzi": "胸中吐万丈长虹。",
        "pinyin": "xiōng zhōng tǔ wàn zhàng cháng hóng."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-er-dong-1",
    "title": "声律启蒙 · 二冬 其一",
    "pinyinTitle": "shēng lǜ qǐ méng · èr dōng qí yī",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "春对夏，",
        "pinyin": "chūn duì xià,"
      },
      {
        "hanzi": "秋对冬，",
        "pinyin": "qiū duì dōng,"
      },
      {
        "hanzi": "暮鼓对晨钟。",
        "pinyin": "mù gǔ duì chén zhōng."
      },
      {
        "hanzi": "观山对玩水，",
        "pinyin": "guān shān duì wán shuǐ,"
      },
      {
        "hanzi": "绿竹对苍松。",
        "pinyin": "lǜ zhú duì cāng sōng."
      },
      {
        "hanzi": "冯妇虎，",
        "pinyin": "féng fù hǔ,"
      },
      {
        "hanzi": "叶公龙，",
        "pinyin": "yè gōng lóng,"
      },
      {
        "hanzi": "舞蝶对鸣蛩。",
        "pinyin": "wǔ dié duì míng qióng."
      },
      {
        "hanzi": "衔泥双紫燕，",
        "pinyin": "xián ní shuāng zǐ yàn,"
      },
      {
        "hanzi": "课蜜几黄蜂。",
        "pinyin": "kè mì jǐ huáng fēng."
      },
      {
        "hanzi": "春日园中莺恰恰，",
        "pinyin": "chūn rì yuán zhōng yīng qià qià,"
      },
      {
        "hanzi": "秋天塞外雁雍雍。",
        "pinyin": "qiū tiān sài wài yàn yōng yōng."
      },
      {
        "hanzi": "秦岭云横，",
        "pinyin": "qín lǐng yún héng,"
      },
      {
        "hanzi": "迢递八千远路；",
        "pinyin": "tiáo dì bā qiān yuǎn lù;"
      },
      {
        "hanzi": "巫山雨洗，",
        "pinyin": "wū shān yǔ xǐ,"
      },
      {
        "hanzi": "嵯峨十二危峰。",
        "pinyin": "cuó é shí èr wēi fēng."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-er-dong-2",
    "title": "声律启蒙 · 二冬 其二",
    "pinyinTitle": "shēng lǜ qǐ méng · èr dōng qí èr",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "明对暗，",
        "pinyin": "míng duì àn,"
      },
      {
        "hanzi": "淡对浓，",
        "pinyin": "dàn duì nóng,"
      },
      {
        "hanzi": "上智对中庸。",
        "pinyin": "shàng zhì duì zhōng yōng."
      },
      {
        "hanzi": "镜奁对衣笥，",
        "pinyin": "jìng lián duì yī sì,"
      },
      {
        "hanzi": "野杵对村舂。",
        "pinyin": "yě chǔ duì cūn chōng."
      },
      {
        "hanzi": "花灼烁，",
        "pinyin": "huā zhuó shuò,"
      },
      {
        "hanzi": "草蒙茸，",
        "pinyin": "cǎo méng róng,"
      },
      {
        "hanzi": "九夏对三冬。",
        "pinyin": "jiǔ xià duì sān dōng."
      },
      {
        "hanzi": "台高名戏马，",
        "pinyin": "tái gāo míng xì mǎ,"
      },
      {
        "hanzi": "斋小号蟠龙。",
        "pinyin": "zhāi xiǎo hào pán lóng."
      },
      {
        "hanzi": "手擘蟹螯从毕卓，",
        "pinyin": "shǒu bò xiè áo cóng bì zhuó,"
      },
      {
        "hanzi": "身披鹤氅自王恭。",
        "pinyin": "shēn pī hè chǎng zì wáng gōng."
      },
      {
        "hanzi": "五老峰高，",
        "pinyin": "wǔ lǎo fēng gāo,"
      },
      {
        "hanzi": "秀插云霄如玉笔；",
        "pinyin": "xiù chā yún xiāo rú yù bǐ;"
      },
      {
        "hanzi": "三姑石大，",
        "pinyin": "sān gū shí dà,"
      },
      {
        "hanzi": "响传风雨若金镛。",
        "pinyin": "xiǎng chuán fēng yǔ ruò jīn yōng."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-er-dong-3",
    "title": "声律启蒙 · 二冬 其三",
    "pinyinTitle": "shēng lǜ qǐ méng · èr dōng qí sān",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "仁对义，",
        "pinyin": "rén duì yì,"
      },
      {
        "hanzi": "让对恭，",
        "pinyin": "ràng duì gōng,"
      },
      {
        "hanzi": "禹舜对羲农。",
        "pinyin": "yǔ shùn duì xī nóng."
      },
      {
        "hanzi": "雪花对云叶，",
        "pinyin": "xuě huā duì yún yè,"
      },
      {
        "hanzi": "芍药对芙蓉。",
        "pinyin": "sháo yào duì fú róng."
      },
      {
        "hanzi": "陈后主，",
        "pinyin": "chén hòu zhǔ,"
      },
      {
        "hanzi": "汉中宗，",
        "pinyin": "hàn zhōng zōng,"
      },
      {
        "hanzi": "绣虎对雕龙。",
        "pinyin": "xiù hǔ duì diāo lóng."
      },
      {
        "hanzi": "柳塘风淡淡，",
        "pinyin": "liǔ táng fēng dàn dàn,"
      },
      {
        "hanzi": "花圃月浓浓。",
        "pinyin": "huā pǔ yuè nóng nóng."
      },
      {
        "hanzi": "春日正宜朝看蝶，",
        "pinyin": "chūn rì zhèng yí cháo kàn dié,"
      },
      {
        "hanzi": "秋风那更夜闻蛩。",
        "pinyin": "qiū fēng nà gèng yè wén qióng."
      },
      {
        "hanzi": "战士邀功，",
        "pinyin": "zhàn shì yāo gōng,"
      },
      {
        "hanzi": "必借干戈成勇武；",
        "pinyin": "bì jiè gān gē chéng yǒng wǔ;"
      },
      {
        "hanzi": "逸民适志，",
        "pinyin": "yì mín shì zhì,"
      },
      {
        "hanzi": "须凭诗酒养疏慵。",
        "pinyin": "xū píng shī jiǔ yǎng shū yōng."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-san-jiang-1",
    "title": "声律启蒙 · 三江 其一",
    "pinyinTitle": "shēng lǜ qǐ méng · sān jiāng qí yī",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "楼对阁，",
        "pinyin": "lóu duì gé,"
      },
      {
        "hanzi": "户对窗，",
        "pinyin": "hù duì chuāng,"
      },
      {
        "hanzi": "巨海对长江。",
        "pinyin": "jù hǎi duì cháng jiāng."
      },
      {
        "hanzi": "蓉裳对蕙帐，",
        "pinyin": "róng shang duì huì zhàng,"
      },
      {
        "hanzi": "玉斝对银釭。",
        "pinyin": "yù jiǎ duì yín gāng."
      },
      {
        "hanzi": "青布幔，",
        "pinyin": "qīng bù màn,"
      },
      {
        "hanzi": "碧油幢，",
        "pinyin": "bì yóu zhuàng,"
      },
      {
        "hanzi": "宝剑对金缸。",
        "pinyin": "bǎo jiàn duì jīn gāng."
      },
      {
        "hanzi": "忠心安社稷，",
        "pinyin": "zhōng xīn ān shè jì,"
      },
      {
        "hanzi": "利口覆家邦。",
        "pinyin": "lì kǒu fù jiā bāng."
      },
      {
        "hanzi": "世祖中兴延马武，",
        "pinyin": "shì zǔ zhōng xīng yán mǎ wǔ,"
      },
      {
        "hanzi": "桀王失道杀龙逄。",
        "pinyin": "jié wáng shī dào shā lóng páng."
      },
      {
        "hanzi": "秋雨潇潇，",
        "pinyin": "qiū yǔ xiāo xiāo,"
      },
      {
        "hanzi": "漫烂黄花都满径；",
        "pinyin": "màn làn huáng huā dōu mǎn jìng;"
      },
      {
        "hanzi": "春风袅袅，",
        "pinyin": "chūn fēng niǎo niǎo,"
      },
      {
        "hanzi": "扶疏绿竹正盈窗。",
        "pinyin": "fú shū lǜ zhú zhèng yíng chuāng."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-san-jiang-2",
    "title": "声律启蒙 · 三江 其二",
    "pinyinTitle": "shēng lǜ qǐ méng · sān jiāng qí èr",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "旌对旆，",
        "pinyin": "jīng duì pèi,"
      },
      {
        "hanzi": "盖对幢，",
        "pinyin": "gài duì zhuàng,"
      },
      {
        "hanzi": "故国对他邦。",
        "pinyin": "gù guó duì tā bāng."
      },
      {
        "hanzi": "千山对万水，",
        "pinyin": "qiān shān duì wàn shuǐ,"
      },
      {
        "hanzi": "九泽对三江。",
        "pinyin": "jiǔ zé duì sān jiāng."
      },
      {
        "hanzi": "山岌岌，",
        "pinyin": "shān jí jí,"
      },
      {
        "hanzi": "水淙淙，",
        "pinyin": "shuǐ cóng cóng,"
      },
      {
        "hanzi": "鼓振对钟撞。",
        "pinyin": "gǔ zhèn duì zhōng zhuàng."
      },
      {
        "hanzi": "清风生酒舍，",
        "pinyin": "qīng fēng shēng jiǔ shè,"
      },
      {
        "hanzi": "皓月照书窗。",
        "pinyin": "hào yuè zhào shū chuāng."
      },
      {
        "hanzi": "阵上倒戈辛纣战，",
        "pinyin": "zhèn shàng dǎo gē xīn zhòu zhàn,"
      },
      {
        "hanzi": "道旁系剑子婴降。",
        "pinyin": "dào páng xì jiàn zǐ yīng jiàng."
      },
      {
        "hanzi": "夏日池塘，",
        "pinyin": "xià rì chí táng,"
      },
      {
        "hanzi": "出没浴波鸥对对；",
        "pinyin": "chū mò yù bō ōu duì duì;"
      },
      {
        "hanzi": "春风帘幕，",
        "pinyin": "chūn fēng lián mù,"
      },
      {
        "hanzi": "往来营垒燕双双。",
        "pinyin": "wǎng lái yíng lěi yàn shuāng shuāng."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-san-jiang-3",
    "title": "声律启蒙 · 三江 其三",
    "pinyinTitle": "shēng lǜ qǐ méng · sān jiāng qí sān",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "铢对两，",
        "pinyin": "zhū duì liǎng,"
      },
      {
        "hanzi": "只对双，",
        "pinyin": "zhī duì shuāng,"
      },
      {
        "hanzi": "华岳对湘江。",
        "pinyin": "huá yuè duì xiāng jiāng."
      },
      {
        "hanzi": "朝车对禁鼓，",
        "pinyin": "cháo chē duì jìn gǔ,"
      },
      {
        "hanzi": "宿火对寒缸。",
        "pinyin": "sù huǒ duì hán gāng."
      },
      {
        "hanzi": "青琐闼，",
        "pinyin": "qīng suǒ tà,"
      },
      {
        "hanzi": "碧纱窗，",
        "pinyin": "bì shā chuāng,"
      },
      {
        "hanzi": "汉社对周邦。",
        "pinyin": "hàn shè duì zhōu bāng."
      },
      {
        "hanzi": "笙箫鸣细细，",
        "pinyin": "shēng xiāo míng xì xì,"
      },
      {
        "hanzi": "钟鼓响摐摐。",
        "pinyin": "zhōng gǔ xiǎng chuāng chuāng."
      },
      {
        "hanzi": "主簿栖鸾名有览，",
        "pinyin": "zhǔ bó qī luán míng yǒu lǎn,"
      },
      {
        "hanzi": "治中展骥姓惟庞。",
        "pinyin": "zhì zhōng zhǎn jì xìng wéi páng."
      },
      {
        "hanzi": "苏武牧羊，",
        "pinyin": "sū wǔ mù yáng,"
      },
      {
        "hanzi": "雪屡餐于北海；",
        "pinyin": "xuě lǚ cān yú běi hǎi;"
      },
      {
        "hanzi": "庄周活鲋，",
        "pinyin": "zhuāng zhōu huó fù,"
      },
      {
        "hanzi": "水必决于西江。",
        "pinyin": "shuǐ bì jué yú xī jiāng."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-si-zhi-1",
    "title": "声律启蒙 · 四支 其一",
    "pinyinTitle": "shēng lǜ qǐ méng · sì zhī qí yī",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "茶对酒，",
        "pinyin": "chá duì jiǔ,"
      },
      {
        "hanzi": "赋对诗，",
        "pinyin": "fù duì shī,"
      },
      {
        "hanzi": "燕子对莺儿。",
        "pinyin": "yàn zi duì yīng ér."
      },
      {
        "hanzi": "栽花对种竹，",
        "pinyin": "zāi huā duì zhǒng zhú,"
      },
      {
        "hanzi": "落絮对游丝。",
        "pinyin": "luò xù duì yóu sī."
      },
      {
        "hanzi": "四目颉，",
        "pinyin": "sì mù jié,"
      },
      {
        "hanzi": "一足夔，",
        "pinyin": "yì zú kuí,"
      },
      {
        "hanzi": "鸲鹆对鹭鸶。",
        "pinyin": "qú yù duì lù sī."
      },
      {
        "hanzi": "半池红菡萏，",
        "pinyin": "bàn chí hóng hàn dàn,"
      },
      {
        "hanzi": "一架白荼蘼。",
        "pinyin": "yí jià bái tú mí."
      },
      {
        "hanzi": "几阵秋风能应候，",
        "pinyin": "jǐ zhèn qiū fēng néng yìng hòu,"
      },
      {
        "hanzi": "一犁春雨甚知时。",
        "pinyin": "yì lí chūn yǔ shèn zhī shí."
      },
      {
        "hanzi": "智伯恩深，",
        "pinyin": "zhì bó ēn shēn,"
      },
      {
        "hanzi": "国士吞变形之炭；",
        "pinyin": "guó shì tūn biàn xíng zhī tàn;"
      },
      {
        "hanzi": "羊公德大，",
        "pinyin": "yáng gōng dé dà,"
      },
      {
        "hanzi": "邑人竖堕泪之碑。",
        "pinyin": "yì rén shù duò lèi zhī bēi."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-si-zhi-2",
    "title": "声律启蒙 · 四支 其二",
    "pinyinTitle": "shēng lǜ qǐ méng · sì zhī qí èr",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "行对止，",
        "pinyin": "xíng duì zhǐ,"
      },
      {
        "hanzi": "速对迟，",
        "pinyin": "sù duì chí,"
      },
      {
        "hanzi": "舞剑对围棋。",
        "pinyin": "wǔ jiàn duì wéi qí."
      },
      {
        "hanzi": "花笺对草字，",
        "pinyin": "huā jiān duì cǎo zì,"
      },
      {
        "hanzi": "竹简对毛锥。",
        "pinyin": "zhú jiǎn duì máo zhuī."
      },
      {
        "hanzi": "汾水鼎，",
        "pinyin": "fén shuǐ dǐng,"
      },
      {
        "hanzi": "岘山碑，",
        "pinyin": "xiàn shān bēi,"
      },
      {
        "hanzi": "虎豹对熊罴。",
        "pinyin": "hǔ bào duì xióng pí."
      },
      {
        "hanzi": "花开红锦绣，",
        "pinyin": "huā kāi hóng jǐn xiù,"
      },
      {
        "hanzi": "水漾碧琉璃。",
        "pinyin": "shuǐ yàng bì liú lí."
      },
      {
        "hanzi": "去妇因探邻舍枣，",
        "pinyin": "qù fù yīn tàn lín shè zǎo,"
      },
      {
        "hanzi": "出妻为种后园葵。",
        "pinyin": "chū qī wèi zhǒng hòu yuán kuí."
      },
      {
        "hanzi": "笛韵和谐，",
        "pinyin": "dí yùn hé xié,"
      },
      {
        "hanzi": "仙管恰从云里降；",
        "pinyin": "xiān guǎn qià cóng yún lǐ jiàng;"
      },
      {
        "hanzi": "橹声咿轧，",
        "pinyin": "lǔ shēng yī yà,"
      },
      {
        "hanzi": "渔舟正向雪中移。",
        "pinyin": "yú zhōu zhèng xiàng xuě zhōng yí."
      }
    ]
  },
  {
    "slug": "sheng-lv-qi-meng-si-zhi-3",
    "title": "声律启蒙 · 四支 其三",
    "pinyinTitle": "shēng lǜ qǐ méng · sì zhī qí sān",
    "author": "车万育",
    "dynasty": "清",
    "form": "蒙学顺口溜",
    "lines": [
      {
        "hanzi": "戈对甲，",
        "pinyin": "gē duì jiǎ,"
      },
      {
        "hanzi": "鼓对旗，",
        "pinyin": "gǔ duì qí,"
      },
      {
        "hanzi": "紫燕对黄鹂。",
        "pinyin": "zǐ yàn duì huáng lí."
      },
      {
        "hanzi": "梅酸对李苦，",
        "pinyin": "méi suān duì lǐ kǔ,"
      },
      {
        "hanzi": "青眼对白眉。",
        "pinyin": "qīng yǎn duì bái méi."
      },
      {
        "hanzi": "三弄笛，",
        "pinyin": "sān nòng dí,"
      },
      {
        "hanzi": "一围棋，",
        "pinyin": "yì wéi qí,"
      },
      {
        "hanzi": "雨打对风吹。",
        "pinyin": "yǔ dǎ duì fēng chuī."
      },
      {
        "hanzi": "海棠春睡早，",
        "pinyin": "hǎi táng chūn shuì zǎo,"
      },
      {
        "hanzi": "杨柳昼眠迟。",
        "pinyin": "yáng liǔ zhòu mián chí."
      },
      {
        "hanzi": "张骏曾为槐树赋，",
        "pinyin": "zhāng jùn céng wèi huái shù fù,"
      },
      {
        "hanzi": "杜陵不作海棠诗。",
        "pinyin": "dù líng bú zuò hǎi táng shī."
      },
      {
        "hanzi": "晋士特奇，",
        "pinyin": "jìn shì tè qí,"
      },
      {
        "hanzi": "可比一斑之豹；",
        "pinyin": "kě bǐ yì bān zhī bào;"
      },
      {
        "hanzi": "唐儒博识，",
        "pinyin": "táng rú bó shí,"
      },
      {
        "hanzi": "堪为五总之龟。",
        "pinyin": "kān wèi wǔ zǒng zhī guī."
      }
    ]
  }
];
