import type { ChinesePoem } from "@/content-schema/read-aloud";

/**
 * 古诗启蒙 — the classical poems Chinese families recite to small children,
 * with full-line pinyin so hard characters never stop the reader. All texts
 * are Tang/classical works, long in the public domain. Pinyin follows the
 * children's-book convention of marking tone sandhi (yí dào, bú jìn).
 */
export const chinesePoems: ChinesePoem[] = [
  {
    slug: "yong-e",
    title: "咏鹅",
    pinyinTitle: "yǒng é",
    author: "骆宾王",
    dynasty: "唐",
    lines: [
      { hanzi: "鹅，鹅，鹅，", pinyin: "é, é, é," },
      { hanzi: "曲项向天歌。", pinyin: "qū xiàng xiàng tiān gē." },
      { hanzi: "白毛浮绿水，", pinyin: "bái máo fú lǜ shuǐ," },
      { hanzi: "红掌拨清波。", pinyin: "hóng zhǎng bō qīng bō." },
    ],
  },
  {
    slug: "jing-ye-si",
    title: "静夜思",
    pinyinTitle: "jìng yè sī",
    author: "李白",
    dynasty: "唐",
    lines: [
      { hanzi: "床前明月光，", pinyin: "chuáng qián míng yuè guāng," },
      { hanzi: "疑是地上霜。", pinyin: "yí shì dì shàng shuāng." },
      { hanzi: "举头望明月，", pinyin: "jǔ tóu wàng míng yuè," },
      { hanzi: "低头思故乡。", pinyin: "dī tóu sī gù xiāng." },
    ],
  },
  {
    slug: "chun-xiao",
    title: "春晓",
    pinyinTitle: "chūn xiǎo",
    author: "孟浩然",
    dynasty: "唐",
    lines: [
      { hanzi: "春眠不觉晓，", pinyin: "chūn mián bù jué xiǎo," },
      { hanzi: "处处闻啼鸟。", pinyin: "chù chù wén tí niǎo." },
      { hanzi: "夜来风雨声，", pinyin: "yè lái fēng yǔ shēng," },
      { hanzi: "花落知多少。", pinyin: "huā luò zhī duō shǎo." },
    ],
  },
  {
    slug: "min-nong",
    title: "悯农（其二）",
    pinyinTitle: "mǐn nóng",
    author: "李绅",
    dynasty: "唐",
    lines: [
      { hanzi: "锄禾日当午，", pinyin: "chú hé rì dāng wǔ," },
      { hanzi: "汗滴禾下土。", pinyin: "hàn dī hé xià tǔ." },
      { hanzi: "谁知盘中餐，", pinyin: "shuí zhī pán zhōng cān," },
      { hanzi: "粒粒皆辛苦。", pinyin: "lì lì jiē xīn kǔ." },
    ],
  },
  {
    slug: "deng-guan-que-lou",
    title: "登鹳雀楼",
    pinyinTitle: "dēng guàn què lóu",
    author: "王之涣",
    dynasty: "唐",
    lines: [
      { hanzi: "白日依山尽，", pinyin: "bái rì yī shān jìn," },
      { hanzi: "黄河入海流。", pinyin: "huáng hé rù hǎi liú." },
      { hanzi: "欲穷千里目，", pinyin: "yù qióng qiān lǐ mù," },
      { hanzi: "更上一层楼。", pinyin: "gèng shàng yì céng lóu." },
    ],
  },
  {
    slug: "xiang-si",
    title: "相思",
    pinyinTitle: "xiāng sī",
    author: "王维",
    dynasty: "唐",
    lines: [
      { hanzi: "红豆生南国，", pinyin: "hóng dòu shēng nán guó," },
      { hanzi: "春来发几枝。", pinyin: "chūn lái fā jǐ zhī." },
      { hanzi: "愿君多采撷，", pinyin: "yuàn jūn duō cǎi xié," },
      { hanzi: "此物最相思。", pinyin: "cǐ wù zuì xiāng sī." },
    ],
  },
  {
    slug: "jue-ju",
    title: "绝句",
    pinyinTitle: "jué jù",
    author: "杜甫",
    dynasty: "唐",
    lines: [
      { hanzi: "两个黄鹂鸣翠柳，", pinyin: "liǎng gè huáng lí míng cuì liǔ," },
      { hanzi: "一行白鹭上青天。", pinyin: "yì háng bái lù shàng qīng tiān." },
      { hanzi: "窗含西岭千秋雪，", pinyin: "chuāng hán xī lǐng qiān qiū xuě," },
      { hanzi: "门泊东吴万里船。", pinyin: "mén bó dōng wú wàn lǐ chuán." },
    ],
  },
  {
    slug: "jiang-xue",
    title: "江雪",
    pinyinTitle: "jiāng xuě",
    author: "柳宗元",
    dynasty: "唐",
    lines: [
      { hanzi: "千山鸟飞绝，", pinyin: "qiān shān niǎo fēi jué," },
      { hanzi: "万径人踪灭。", pinyin: "wàn jìng rén zōng miè." },
      { hanzi: "孤舟蓑笠翁，", pinyin: "gū zhōu suō lì wēng," },
      { hanzi: "独钓寒江雪。", pinyin: "dú diào hán jiāng xuě." },
    ],
  },
  {
    slug: "you-zi-yin",
    title: "游子吟",
    pinyinTitle: "yóu zǐ yín",
    author: "孟郊",
    dynasty: "唐",
    lines: [
      { hanzi: "慈母手中线，", pinyin: "cí mǔ shǒu zhōng xiàn," },
      { hanzi: "游子身上衣。", pinyin: "yóu zǐ shēn shàng yī." },
      { hanzi: "临行密密缝，", pinyin: "lín xíng mì mì féng," },
      { hanzi: "意恐迟迟归。", pinyin: "yì kǒng chí chí guī." },
      { hanzi: "谁言寸草心，", pinyin: "shuí yán cùn cǎo xīn," },
      { hanzi: "报得三春晖。", pinyin: "bào dé sān chūn huī." },
    ],
  },
  {
    slug: "chi-shang",
    title: "池上",
    pinyinTitle: "chí shàng",
    author: "白居易",
    dynasty: "唐",
    lines: [
      { hanzi: "小娃撑小艇，", pinyin: "xiǎo wá chēng xiǎo tǐng," },
      { hanzi: "偷采白莲回。", pinyin: "tōu cǎi bái lián huí." },
      { hanzi: "不解藏踪迹，", pinyin: "bù jiě cáng zōng jì," },
      { hanzi: "浮萍一道开。", pinyin: "fú píng yí dào kāi." },
    ],
  },
  {
    slug: "cao",
    title: "草（节选）",
    pinyinTitle: "cǎo",
    author: "白居易",
    dynasty: "唐",
    lines: [
      { hanzi: "离离原上草，", pinyin: "lí lí yuán shàng cǎo," },
      { hanzi: "一岁一枯荣。", pinyin: "yí suì yì kū róng." },
      { hanzi: "野火烧不尽，", pinyin: "yě huǒ shāo bú jìn," },
      { hanzi: "春风吹又生。", pinyin: "chūn fēng chuī yòu shēng." },
    ],
  },
  {
    slug: "wang-lu-shan-pu-bu",
    title: "望庐山瀑布",
    pinyinTitle: "wàng lú shān pù bù",
    author: "李白",
    dynasty: "唐",
    lines: [
      { hanzi: "日照香炉生紫烟，", pinyin: "rì zhào xiāng lú shēng zǐ yān," },
      { hanzi: "遥看瀑布挂前川。", pinyin: "yáo kàn pù bù guà qián chuān." },
      { hanzi: "飞流直下三千尺，", pinyin: "fēi liú zhí xià sān qiān chǐ," },
      { hanzi: "疑是银河落九天。", pinyin: "yí shì yín hé luò jiǔ tiān." },
    ],
  },
  {
    slug: "shan-xing",
    title: "山行",
    pinyinTitle: "shān xíng",
    author: "杜牧",
    dynasty: "唐",
    lines: [
      { hanzi: "远上寒山石径斜，", pinyin: "yuǎn shàng hán shān shí jìng xié," },
      { hanzi: "白云生处有人家。", pinyin: "bái yún shēng chù yǒu rén jiā." },
      { hanzi: "停车坐爱枫林晚，", pinyin: "tíng chē zuò ài fēng lín wǎn," },
      { hanzi: "霜叶红于二月花。", pinyin: "shuāng yè hóng yú èr yuè huā." },
    ],
  },
  {
    slug: "lu-zhai",
    title: "鹿柴",
    pinyinTitle: "lù zhài",
    author: "王维",
    dynasty: "唐",
    lines: [
      { hanzi: "空山不见人，", pinyin: "kōng shān bú jiàn rén," },
      { hanzi: "但闻人语响。", pinyin: "dàn wén rén yǔ xiǎng." },
      { hanzi: "返景入深林，", pinyin: "fǎn jǐng rù shēn lín," },
      { hanzi: "复照青苔上。", pinyin: "fù zhào qīng tái shàng." },
    ],
  },
  {
    slug: "zao-fa-bai-di-cheng",
    title: "早发白帝城",
    pinyinTitle: "zǎo fā bái dì chéng",
    author: "李白",
    dynasty: "唐",
    lines: [
      { hanzi: "朝辞白帝彩云间，", pinyin: "zhāo cí bái dì cǎi yún jiān," },
      { hanzi: "千里江陵一日还。", pinyin: "qiān lǐ jiāng líng yí rì huán." },
      { hanzi: "两岸猿声啼不住，", pinyin: "liǎng àn yuán shēng tí bú zhù," },
      { hanzi: "轻舟已过万重山。", pinyin: "qīng zhōu yǐ guò wàn chóng shān." },
    ],
  },
  {
    slug: "jue-ju-chi-ri",
    title: "绝句·迟日江山丽",
    pinyinTitle: "jué jù · chí rì jiāng shān lì",
    author: "杜甫",
    dynasty: "唐",
    lines: [
      { hanzi: "迟日江山丽，", pinyin: "chí rì jiāng shān lì," },
      { hanzi: "春风花草香。", pinyin: "chūn fēng huā cǎo xiāng." },
      { hanzi: "泥融飞燕子，", pinyin: "ní róng fēi yàn zǐ," },
      { hanzi: "沙暖睡鸳鸯。", pinyin: "shā nuǎn shuì yuān yāng." },
    ],
  },
  {
    slug: "feng",
    title: "风",
    pinyinTitle: "fēng",
    author: "李峤",
    dynasty: "唐",
    lines: [
      { hanzi: "解落三秋叶，", pinyin: "jiě luò sān qiū yè," },
      { hanzi: "能开二月花。", pinyin: "néng kāi èr yuè huā." },
      { hanzi: "过江千尺浪，", pinyin: "guò jiāng qiān chǐ làng," },
      { hanzi: "入竹万竿斜。", pinyin: "rù zhú wàn gān xié." },
    ],
  },
  {
    slug: "xun-yin-zhe-bu-yu",
    title: "寻隐者不遇",
    pinyinTitle: "xún yǐn zhě bú yù",
    author: "贾岛",
    dynasty: "唐",
    lines: [
      { hanzi: "松下问童子，", pinyin: "sōng xià wèn tóng zǐ," },
      { hanzi: "言师采药去。", pinyin: "yán shī cǎi yào qù." },
      { hanzi: "只在此山中，", pinyin: "zhǐ zài cǐ shān zhōng," },
      { hanzi: "云深不知处。", pinyin: "yún shēn bù zhī chù." },
    ],
  },
  {
    slug: "hua",
    title: "画",
    pinyinTitle: "huà",
    author: "王维（传）",
    dynasty: "唐",
    lines: [
      { hanzi: "远看山有色，", pinyin: "yuǎn kàn shān yǒu sè," },
      { hanzi: "近听水无声。", pinyin: "jìn tīng shuǐ wú shēng." },
      { hanzi: "春去花还在，", pinyin: "chūn qù huā hái zài," },
      { hanzi: "人来鸟不惊。", pinyin: "rén lái niǎo bù jīng." },
    ],
  },
  {
    slug: "shan-cun-yong-huai",
    title: "山村咏怀",
    pinyinTitle: "shān cūn yǒng huái",
    author: "邵雍",
    dynasty: "宋",
    lines: [
      { hanzi: "一去二三里，", pinyin: "yí qù èr sān lǐ," },
      { hanzi: "烟村四五家。", pinyin: "yān cūn sì wǔ jiā." },
      { hanzi: "亭台六七座，", pinyin: "tíng tái liù qī zuò," },
      { hanzi: "八九十枝花。", pinyin: "bā jiǔ shí zhī huā." },
    ],
  },
  {
    slug: "xiao-chi",
    title: "小池",
    pinyinTitle: "xiǎo chí",
    author: "杨万里",
    dynasty: "宋",
    lines: [
      { hanzi: "泉眼无声惜细流，", pinyin: "quán yǎn wú shēng xī xì liú," },
      { hanzi: "树阴照水爱晴柔。", pinyin: "shù yīn zhào shuǐ ài qíng róu." },
      { hanzi: "小荷才露尖尖角，", pinyin: "xiǎo hé cái lù jiān jiān jiǎo," },
      { hanzi: "早有蜻蜓立上头。", pinyin: "zǎo yǒu qīng tíng lì shàng tóu." },
    ],
  },
  {
    slug: "suo-jian",
    title: "所见",
    pinyinTitle: "suǒ jiàn",
    author: "袁枚",
    dynasty: "清",
    lines: [
      { hanzi: "牧童骑黄牛，", pinyin: "mù tóng qí huáng niú," },
      { hanzi: "歌声振林樾。", pinyin: "gē shēng zhèn lín yuè." },
      { hanzi: "意欲捕鸣蝉，", pinyin: "yì yù bǔ míng chán," },
      { hanzi: "忽然闭口立。", pinyin: "hū rán bì kǒu lì." },
    ],
  },
  {
    slug: "cun-ju",
    title: "村居",
    pinyinTitle: "cūn jū",
    author: "高鼎",
    dynasty: "清",
    lines: [
      { hanzi: "草长莺飞二月天，", pinyin: "cǎo zhǎng yīng fēi èr yuè tiān," },
      { hanzi: "拂堤杨柳醉春烟。", pinyin: "fú dī yáng liǔ zuì chūn yān." },
      { hanzi: "儿童散学归来早，", pinyin: "ér tóng sàn xué guī lái zǎo," },
      { hanzi: "忙趁东风放纸鸢。", pinyin: "máng chèn dōng fēng fàng zhǐ yuān." },
    ],
  },
  {
    slug: "qing-ming",
    title: "清明",
    pinyinTitle: "qīng míng",
    author: "杜牧",
    dynasty: "唐",
    lines: [
      { hanzi: "清明时节雨纷纷，", pinyin: "qīng míng shí jié yǔ fēn fēn," },
      { hanzi: "路上行人欲断魂。", pinyin: "lù shàng xíng rén yù duàn hún." },
      { hanzi: "借问酒家何处有，", pinyin: "jiè wèn jiǔ jiā hé chù yǒu," },
      { hanzi: "牧童遥指杏花村。", pinyin: "mù tóng yáo zhǐ xìng huā cūn." },
    ],
  },
];
