import type { EnglishPiece } from "@/content-schema/read-aloud";

/**
 * GENERATED by scripts/gen-read-aloud.mjs — edit the manifest there and
 * regenerate; do not hand-edit. Sources: Project Gutenberg #10607 (The Real
 * Mother Goose), #25609 (A Child's Garden of Verses), #13650 (Lear's
 * Nonsense Songs), and PoetryDB. All public domain.
 */
export const englishPieces: EnglishPiece[] = [
  {
    "slug": "twinkle-twinkle",
    "title": "Twinkle, Twinkle, Little Star",
    "author": "Jane Taylor",
    "kind": "rhyme",
    "stanzas": [
      [
        "Twinkle, twinkle, little star,",
        "How I wonder what you are !",
        "Up above the world so high,",
        "Like a diamond in the sky."
      ],
      [
        "When the blazing sun is gone,",
        "When he nothing shines upon,",
        "Then you show your little light,",
        "Twinkle, twinkle, all the night."
      ],
      [
        "Then the trav'ller in the dark,",
        "Thanks you for your tiny spark,",
        "He could not see which way to go,",
        "If you did not twinkle so."
      ],
      [
        "In the dark blue sky you keep,",
        "And often thro' my curtains peep,",
        "For you never shut your eye,",
        "Till the sun is in the sky."
      ],
      [
        "'Tis your bright and tiny spark,",
        "Lights the trav'ller in the dark :",
        "Tho' I know not what you are,",
        "Twinkle, twinkle, little star."
      ]
    ]
  },
  {
    "slug": "humpty-dumpty",
    "title": "Humpty Dumpty",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Humpty Dumpty sat on a wall,",
        "Humpty Dumpty had a great fall;",
        "All the King's horses, and all the King's men",
        "Cannot put Humpty Dumpty together again."
      ]
    ]
  },
  {
    "slug": "jack-and-jill",
    "title": "Jack and Jill",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Jack and Jill went up the hill,",
        "To fetch a pail of water;",
        "Jack fell down, and broke his crown,",
        "And Jill came tumbling after."
      ],
      [
        "Then up Jack got and off did trot,",
        "As fast as he could caper,",
        "To old Dame Dob, who patched his nob",
        "With vinegar and brown paper."
      ]
    ]
  },
  {
    "slug": "baa-baa-black-sheep",
    "title": "Baa, Baa, Black Sheep",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Baa, baa, black sheep,",
        "Have you any wool?",
        "Yes, marry, have I,",
        "Three bags full;"
      ],
      [
        "One for my master,",
        "One for my dame,",
        "But none for the little boy",
        "Who cries in the lane."
      ]
    ]
  },
  {
    "slug": "hey-diddle-diddle",
    "title": "Hey Diddle Diddle",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Hey, diddle, diddle!",
        "The cat and the fiddle,",
        "The cow jumped over the moon;",
        "The little dog laughed",
        "To see such sport,",
        "And the dish ran away with the spoon."
      ]
    ]
  },
  {
    "slug": "hickory-dickory-dock",
    "title": "Hickory, Dickory, Dock",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Hickory, dickory, dock!",
        "The mouse ran up the clock;",
        "The clock struck one,",
        "And down he run,",
        "Hickory, dickory, dock!"
      ]
    ]
  },
  {
    "slug": "little-miss-muffet",
    "title": "Little Miss Muffet",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Little Miss Muffet",
        "Sat on a tuffet,",
        "Eating of curds and whey;",
        "There came a big spider,",
        "And sat down beside her,",
        "And frightened Miss Muffet away."
      ]
    ]
  },
  {
    "slug": "pat-a-cake",
    "title": "Pat-a-Cake",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Pat-a-cake, pat-a-cake,",
        "Baker's man!",
        "So I do, master,",
        "As fast as I can."
      ],
      [
        "Pat it, and prick it,",
        "And mark it with T,",
        "Put it in the oven",
        "For Tommy and me."
      ]
    ]
  },
  {
    "slug": "little-bo-peep",
    "title": "Little Bo-Peep",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Little Bo-Peep has lost her sheep,",
        "And can't tell where to find them;",
        "Leave them alone, and they'll come home,",
        "And bring their tails behind them."
      ],
      [
        "Little Bo-Peep fell fast asleep,",
        "And dreamt she heard them bleating;",
        "But when she awoke, she found it a joke,",
        "For still they all were fleeting."
      ],
      [
        "Then up she took her little crook,",
        "Determined for to find them;",
        "She found them indeed, but it made her heart bleed,",
        "For they'd left all their tails behind 'em!"
      ],
      [
        "It happened one day, as Bo-peep did stray",
        "Unto a meadow hard by--",
        "There she espied their tails, side by side,",
        "All hung on a tree to dry."
      ],
      [
        "She heaved a sigh and wiped her eye,",
        "And over the hillocks she raced;",
        "And tried what she could, as a shepherdess should,",
        "That each tail should be properly placed."
      ]
    ]
  },
  {
    "slug": "little-boy-blue",
    "title": "Little Boy Blue",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Little Boy Blue, come, blow your horn!",
        "The sheep's in the meadow, the cow's in the corn.",
        "Where's the little boy that looks after the sheep?",
        "Under the haystack, fast asleep!"
      ]
    ]
  },
  {
    "slug": "rock-a-bye-baby",
    "title": "Rock-a-Bye, Baby",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Rock-a-bye, baby, thy cradle is green;",
        "Father's a nobleman, mother's a queen;",
        "And Betty's a lady, and wears a gold ring;",
        "And Johnny's a drummer, and drums for the king."
      ]
    ]
  },
  {
    "slug": "sleep-baby-sleep",
    "title": "Sleep, Baby, Sleep",
    "author": "Traditional",
    "kind": "rhyme",
    "stanzas": [
      [
        "Sleep, baby, sleep,",
        "Our cottage vale is deep:",
        "The little lamb is on the green,",
        "With woolly fleece so soft and clean--",
        "Sleep, baby, sleep.",
        "Sleep, baby, sleep,",
        "Down where the woodbines creep;",
        "Be always like the lamb so mild,",
        "A kind, and sweet, and gentle child.",
        "Sleep, baby, sleep."
      ]
    ]
  },
  {
    "slug": "the-swing",
    "title": "The Swing",
    "author": "Robert Louis Stevenson",
    "kind": "poem",
    "stanzas": [
      [
        "How do you like to go up in a swing,",
        "Up in the air so blue?",
        "Oh, I do think it the pleasantest thing",
        "Ever a child can do!"
      ],
      [
        "Up in the air and over the wall,",
        "Till I can see so wide,",
        "Rivers and trees and cattle and all",
        "Over the countryside--"
      ],
      [
        "Till I look down on the garden green,",
        "Down on the roof so brown--",
        "Up in the air I go flying again,",
        "Up in the air and down!"
      ]
    ]
  },
  {
    "slug": "rain",
    "title": "Rain",
    "author": "Robert Louis Stevenson",
    "kind": "poem",
    "stanzas": [
      [
        "The rain is raining all around,",
        "It falls on field and tree,",
        "It rains on the umbrellas here,",
        "And on the ships at sea."
      ]
    ]
  },
  {
    "slug": "owl-and-the-pussy-cat",
    "title": "The Owl and the Pussy-Cat",
    "author": "Edward Lear",
    "kind": "poem",
    "stanzas": [
      [
        "The Owl and the Pussy-Cat went to sea",
        "In a beautiful pea-green boat:",
        "They took some honey, and plenty of money",
        "Wrapped up in a five-pound note.",
        "The Owl looked up to the stars above,",
        "And sang to a small guitar,",
        "\"O lovely Pussy, O Pussy, my love,",
        "What a beautiful Pussy you are,",
        "You are,",
        "You are!",
        "What a beautiful Pussy you are!\""
      ],
      [
        "Pussy said to the Owl, \"You elegant fowl,",
        "How charmingly sweet you sing!",
        "Oh! let us be married; too long we have tarried:",
        "But what shall we do for a ring?\"",
        "They sailed away, for a year and a day,",
        "To the land where the bong-tree grows;",
        "And there in a wood a Piggy-wig stood,",
        "With a ring at the end of his nose,",
        "His nose,",
        "His nose,",
        "With a ring at the end of his nose."
      ],
      [
        "\"Dear Pig, are you willing to sell for one shilling",
        "Your ring?\" Said the Piggy, \"I will.\"",
        "So they took it away, and were married next day",
        "By the Turkey who lives on the hill.",
        "They dined on mince and slices of quince,",
        "Which they ate with a runcible spoon;",
        "And hand in hand, on the edge of the sand,",
        "They danced by the light of the moon,",
        "The moon,",
        "The moon,",
        "They danced by the light of the moon."
      ]
    ]
  },
  {
    "slug": "wynken-blynken-and-nod",
    "title": "Wynken, Blynken, and Nod",
    "author": "Eugene Field",
    "kind": "poem",
    "stanzas": [
      [
        "Wynken, Blynken, and Nod one night",
        "Sailed off in a wooden shoe,--",
        "Sailed on a river of crystal light",
        "Into a sea of dew.",
        "\"Where are you going, and what do you wish?\"",
        "The old moon asked the three.",
        "\"We have come to fish for the herring-fish",
        "That live in this beautiful sea;",
        "Nets of silver and gold have we,\"",
        "Said Wynken,",
        "Blynken,",
        "And Nod."
      ],
      [
        "The old moon laughed and sang a song,",
        "As they rocked in the wooden shoe;",
        "And the wind that sped them all night long",
        "Ruffled the waves of dew;",
        "The little stars were the herring-fish",
        "That lived in the beautiful sea.",
        "\"Now cast your nets wherever you wish,--",
        "Never afraid are we!\"",
        "So cried the stars to the fishermen three,",
        "Wynken,",
        "Blynken,",
        "And Nod."
      ],
      [
        "All night long their nets they threw",
        "To the stars in the twinkling foam,--",
        "Then down from the skies came the wooden shoe,",
        "Bringing the fishermen home:",
        "'Twas all so pretty a sail, it seemed",
        "As if it could not be;",
        "And some folk thought 'twas a dream they'd dreamed",
        "Of sailing that beautiful sea;",
        "But I shall name you the fishermen three:",
        "Wynken,",
        "Blynken,",
        "And Nod."
      ],
      [
        "Wynken and Blynken are two little eyes,",
        "And Nod is a little head,",
        "And the wooden shoe that sailed the skies",
        "Is a wee one's trundle-bed;",
        "So shut your eyes while Mother sings",
        "Of wonderful sights that be,",
        "And you shall see the beautiful things",
        "As you rock in the misty sea",
        "Where the old shoe rocked the fishermen three:--",
        "Wynken,",
        "Blynken,",
        "And Nod."
      ]
    ]
  },
  {
    "slug": "sonnet-18",
    "title": "Sonnet 18",
    "author": "William Shakespeare",
    "kind": "sonnet",
    "stanzas": [
      [
        "Shall I compare thee to a summer's day?",
        "Thou art more lovely and more temperate:",
        "Rough winds do shake the darling buds of May,",
        "And summer's lease hath all too short a date:",
        "Sometime too hot the eye of heaven shines,",
        "And often is his gold complexion dimm'd,",
        "And every fair from fair sometime declines,",
        "By chance, or nature's changing course untrimm'd:",
        "But thy eternal summer shall not fade,",
        "Nor lose possession of that fair thou ow'st,",
        "Nor shall death brag thou wander'st in his shade,",
        "When in eternal lines to time thou grow'st,",
        "So long as men can breathe, or eyes can see,",
        "So long lives this, and this gives life to thee."
      ]
    ]
  }
];
