import type { Food } from "@/content-schema/food";

/**
 * Aggregated food database. Each food lives in its own file; this index is
 * regenerated by `npm run gen:food-index` (scripts/gen-food-index.ts).
 */
export const allFoods: Food[] = [];
