import type { Food } from "@/content-schema/food";
import almondButter from "./almond-butter";
import apple from "./apple";
import avocado from "./avocado";
import banana from "./banana";
import barley from "./barley";
import beef from "./beef";
import beet from "./beet";
import bellPepper from "./bell-pepper";
import blackBeans from "./black-beans";
import blueberry from "./blueberry";
import bread from "./bread";
import broccoli from "./broccoli";
import butternutSquash from "./butternut-squash";
import carrot from "./carrot";
import cashewButter from "./cashew-butter";
import cauliflower from "./cauliflower";
import cheese from "./cheese";
import cherries from "./cherries";
import chicken from "./chicken";
import chickpeas from "./chickpeas";
import cod from "./cod";
import cucumber from "./cucumber";
import edamame from "./edamame";
import egg from "./egg";
import farina from "./farina";
import grapes from "./grapes";
import greenBeans from "./green-beans";
import kiwi from "./kiwi";
import lamb from "./lamb";
import lentils from "./lentils";
import liver from "./liver";
import mango from "./mango";
import oatCereal from "./oat-cereal";
import oatmeal from "./oatmeal";
import oliveOil from "./olive-oil";
import orange from "./orange";
import pasta from "./pasta";
import peach from "./peach";
import peanutButter from "./peanut-butter";
import pear from "./pear";
import peas from "./peas";
import polenta from "./polenta";
import pork from "./pork";
import potato from "./potato";
import prunes from "./prunes";
import quinoa from "./quinoa";
import raspberry from "./raspberry";
import rice from "./rice";
import salmon from "./salmon";
import sardines from "./sardines";
import shrimp from "./shrimp";
import spinach from "./spinach";
import strawberry from "./strawberry";
import sunflowerSeedButter from "./sunflower-seed-butter";
import sweetPotato from "./sweet-potato";
import tahini from "./tahini";
import tofu from "./tofu";
import tomato from "./tomato";
import turkey from "./turkey";
import walnut from "./walnut";
import watermelon from "./watermelon";
import yogurt from "./yogurt";
import zucchini from "./zucchini";

/**
 * Aggregated food database. Each food lives in its own file; this index is
 * regenerated by `npm run gen:food-index` (scripts/gen-food-index.ts).
 */
export const allFoods: Food[] = [
  almondButter,
  apple,
  avocado,
  banana,
  barley,
  beef,
  beet,
  bellPepper,
  blackBeans,
  blueberry,
  bread,
  broccoli,
  butternutSquash,
  carrot,
  cashewButter,
  cauliflower,
  cheese,
  cherries,
  chicken,
  chickpeas,
  cod,
  cucumber,
  edamame,
  egg,
  farina,
  grapes,
  greenBeans,
  kiwi,
  lamb,
  lentils,
  liver,
  mango,
  oatCereal,
  oatmeal,
  oliveOil,
  orange,
  pasta,
  peach,
  peanutButter,
  pear,
  peas,
  polenta,
  pork,
  potato,
  prunes,
  quinoa,
  raspberry,
  rice,
  salmon,
  sardines,
  shrimp,
  spinach,
  strawberry,
  sunflowerSeedButter,
  sweetPotato,
  tahini,
  tofu,
  tomato,
  turkey,
  walnut,
  watermelon,
  yogurt,
  zucchini,
];

export const foodBySlug = new Map(allFoods.map((f) => [f.slug, f]));
