import type { FamilyRecipe } from "@/content-schema/recipe";
import bananaOatPancakes from "./banana-oat-pancakes";
import beefBroccoliStirFry from "./beef-broccoli-stir-fry";
import chickenCornSoup from "./chicken-corn-soup";
import eggFriedRice from "./egg-fried-rice";
import honeySoySalmonRiceBowl from "./honey-soy-salmon-rice-bowl";
import porkCabbageDumplings from "./pork-cabbage-dumplings";
import seaweedEggDropSoup from "./seaweed-egg-drop-soup";
import steamedEggCustard from "./steamed-egg-custard";
import tomatoBeefNoodleSoup from "./tomato-beef-noodle-soup";
import tomatoEggStirFry from "./tomato-egg-stir-fry";

/**
 * Family-table recipes for school-age kids and the rest of the family.
 * Each recipe lives in its own file; this index is regenerated by
 * `npm run gen:recipe-index`.
 */
export const allFamilyRecipes: FamilyRecipe[] = [
  bananaOatPancakes,
  beefBroccoliStirFry,
  chickenCornSoup,
  eggFriedRice,
  honeySoySalmonRiceBowl,
  porkCabbageDumplings,
  seaweedEggDropSoup,
  steamedEggCustard,
  tomatoBeefNoodleSoup,
  tomatoEggStirFry,
];

export const familyRecipeBySlug = new Map(allFamilyRecipes.map((r) => [r.slug, r]));
