/**
 * Regenerates content/foods/index.ts from the food files in that directory.
 * Each food file default-exports a Food. Run: npm run gen:food-index
 */
import fs from "node:fs";
import path from "node:path";

const FOODS_DIR = path.join(process.cwd(), "content", "foods");

const files = fs
  .readdirSync(FOODS_DIR)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts")
  .sort();

const toIdent = (file: string) =>
  file
    .replace(/\.ts$/, "")
    .replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

const imports = files
  .map((f) => `import ${toIdent(f)} from "./${f.replace(/\.ts$/, "")}";`)
  .join("\n");
const list = files.map((f) => `  ${toIdent(f)},`).join("\n");

const out = `import type { Food } from "@/content-schema/food";
${imports}

/**
 * Aggregated food database. Each food lives in its own file; this index is
 * regenerated by \`npm run gen:food-index\` (scripts/gen-food-index.ts).
 */
export const allFoods: Food[] = [
${list}
];

export const foodBySlug = new Map(allFoods.map((f) => [f.slug, f]));
`;

fs.writeFileSync(path.join(FOODS_DIR, "index.ts"), out);
console.log(`gen-food-index: wrote index with ${files.length} foods.`);
