/**
 * Regenerates content/recipes/index.ts from the recipe files in that
 * directory. Each recipe file default-exports a Recipe. Run:
 * npm run gen:recipe-index
 */
import fs from "node:fs";
import path from "node:path";

const RECIPES_DIR = path.join(process.cwd(), "content", "recipes");

const files = fs
  .readdirSync(RECIPES_DIR)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts")
  .sort();

const toIdent = (file: string) =>
  file
    .replace(/\.ts$/, "")
    .replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

const imports = files
  .map((f) => `import ${toIdent(f)} from "./${f.replace(/\.ts$/, "")}";`)
  .join("\n");
const list = files.map((f) => `  ${toIdent(f)},`).join("\n");

const out = `import type { Recipe } from "@/content-schema/recipe";
${imports}

/**
 * Aggregated recipe corpus (Part III D3). Each recipe lives in its own
 * file; this index is regenerated by \`npm run gen:recipe-index\`.
 */
export const allRecipes: Recipe[] = [
${list}
];

export const recipeBySlug = new Map(allRecipes.map((r) => [r.slug, r]));
`;

fs.writeFileSync(path.join(RECIPES_DIR, "index.ts"), out);
console.log(`gen-recipe-index: wrote index with ${files.length} recipes.`);
