/**
 * Regenerates the index.ts in each content/i18n/zh subdirectory (foods,
 * recipes, guides, allergens) from the overlay files in it. Each overlay
 * file default-exports an L10n object. Run: npm run gen:zh-index
 */
import fs from "node:fs";
import path from "node:path";

const KINDS = [
  { dir: "foods", type: "FoodL10n", constName: "ZH_FOODS", doc: "zh food overlays, keyed by slug" },
  { dir: "recipes", type: "RecipeL10n", constName: "ZH_RECIPES", doc: "zh recipe overlays, keyed by slug" },
  { dir: "guides", type: "GuideL10n", constName: "ZH_GUIDES", doc: "zh guide overlays, keyed by slug" },
  { dir: "allergens", type: "AllergenL10n", constName: "ZH_ALLERGENS", doc: "zh allergen-program overlays, keyed by allergen id" },
] as const;

const toIdent = (file: string) =>
  file
    .replace(/\.ts$/, "")
    .replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

for (const kind of KINDS) {
  const dir = path.join(process.cwd(), "content", "i18n", "zh", kind.dir);
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .sort();

  const imports = files
    .map((f) => `import ${toIdent(f)} from "./${f.replace(/\.ts$/, "")}";`)
    .join("\n");
  const entries = files
    .map((f) => `  [${toIdent(f)}.${kind.dir === "allergens" ? "id" : "slug"}]: ${toIdent(f)},`)
    .join("\n");

  const out = `import type { ${kind.type} } from "@/content-schema/l10n";
${imports ? `${imports}\n` : ""}
/** ${kind.doc} (regenerated by \`npm run gen:zh-index\`). */
export const ${kind.constName}: Record<string, ${kind.type}> = {
${entries}
};
`;

  fs.writeFileSync(path.join(dir, "index.ts"), out);
  console.log(`gen-zh-index: ${kind.dir} — ${files.length} overlays.`);
}
