/**
 * Regenerates content/foods/search-terms.ts — a compact, locale-independent
 * search index so a food is findable by ANY of its common names in either
 * language, whatever language the UI is set to. Chinese users often keep the
 * app in English but type 番茄 / 土豆 / 奇异果; this map carries those names
 * (from the zh overlays) without pulling the heavy zh prose chunk into the
 * search bundle.
 *
 * Terms per slug = lowercased, de-duped [en name, en aliases, zh name,
 * zh aliases]. Run: npm run gen:search-terms
 */
import fs from "node:fs";
import path from "node:path";

async function main() {
  const { allFoods } = await import("../content/foods");
  const { ZH_FOODS } = await import("../content/i18n/zh/foods");

  const entries: string[] = [];
  for (const f of allFoods) {
    const o = ZH_FOODS[f.slug];
    const terms = new Set<string>();
    for (const t of [f.name, ...f.aliases, o?.name, ...(o?.aliases ?? [])]) {
      const s = t?.trim().toLowerCase();
      if (s) terms.add(s);
    }
    const json = JSON.stringify([...terms]);
    entries.push(`  ${JSON.stringify(f.slug)}: ${json},`);
  }

  const out = `// GENERATED by scripts/gen-search-terms.ts — do not edit by hand.
// Run \`npm run gen:search-terms\` after changing a food name/alias or a zh overlay.

/**
 * Cross-language search terms per food slug: every common name in both
 * languages, lowercased. Locale-independent so search works whatever the UI
 * language is. Names only (no prose), so this stays tiny.
 */
export const FOOD_SEARCH_TERMS: Record<string, string[]> = {
${entries.join("\n")}
};
`;

  fs.writeFileSync(path.join(process.cwd(), "content", "foods", "search-terms.ts"), out);
  console.log(`gen-search-terms: wrote terms for ${allFoods.length} foods.`);
}

main();
