import type { RecipeL10n } from "@/content-schema/l10n";
import almondButterAppleStir from "./almond-butter-apple-stir";
import appleCinnamonOatmeal from "./apple-cinnamon-oatmeal";
import bananaPeanutOatMash from "./banana-peanut-oat-mash";
import bananaTahiniToastStrips from "./banana-tahini-toast-strips";
import beefTomatoPolentaMash from "./beef-tomato-polenta-mash";
import blackBeanMangoMash from "./black-bean-mango-mash";
import blueberryPearFreezerCubes from "./blueberry-pear-freezer-cubes";
import blueberryYogurtSwirl from "./blueberry-yogurt-swirl";
import carrotTahiniYogurtBlend from "./carrot-tahini-yogurt-blend";
import chickenBroccoliRiceBlend from "./chicken-broccoli-rice-blend";
import chickpeaTomatoCuminBlend from "./chickpea-tomato-cumin-blend";
import codPotatoLeekMash from "./cod-potato-leek-mash";
import cucumberYogurtDillSauce from "./cucumber-yogurt-dill-sauce";
import dateSweetenedOatmeal from "./date-sweetened-oatmeal";
import edamameBroccoliBlend from "./edamame-broccoli-blend";
import eggAvocadoToastStrips from "./egg-avocado-toast-strips";
import eggSaladToastStrips from "./egg-salad-toast-strips";
import kefirBerrySmoothie from "./kefir-berry-smoothie";
import kiwiOatmealStir from "./kiwi-oatmeal-stir";
import lambSquashKaleCubes from "./lamb-squash-kale-cubes";
import lentilSweetPotatoCubes from "./lentil-sweet-potato-cubes";
import liverSweetPotatoBlend from "./liver-sweet-potato-blend";
import mangoQuinoaBreakfastBowl from "./mango-quinoa-breakfast-bowl";
import peachCottageCheeseWhip from "./peach-cottage-cheese-whip";
import peachRaspberryFreezerCubes from "./peach-raspberry-freezer-cubes";
import pearPruneMash from "./pear-prune-mash";
import porkAppleParsnipMash from "./pork-apple-parsnip-mash";
import pumpkinPieYogurt from "./pumpkin-pie-yogurt";
import quinoaVeggieCubes from "./quinoa-veggie-cubes";
import raspberryAmaranthPorridge from "./raspberry-amaranth-porridge";
import redLentilTomatoCubes from "./red-lentil-tomato-cubes";
import salmonAvocadoSmash from "./salmon-avocado-smash";
import sardineTomatoSmash from "./sardine-tomato-smash";
import scrambledEggAvocadoMash from "./scrambled-egg-avocado-mash";
import shrimpPeaRiceBlend from "./shrimp-pea-rice-blend";
import strawberryChiaJam from "./strawberry-chia-jam";
import strawberryFarinaPorridge from "./strawberry-farina-porridge";
import tofuRedPepperSmash from "./tofu-red-pepper-smash";
import turkeyTomatoCouscous from "./turkey-tomato-couscous";
import whiteBeanSpinachCubes from "./white-bean-spinach-cubes";

/** zh recipe overlays, keyed by slug (regenerated by `npm run gen:zh-index`). */
export const ZH_RECIPES: Record<string, RecipeL10n> = {
  [almondButterAppleStir.slug]: almondButterAppleStir,
  [appleCinnamonOatmeal.slug]: appleCinnamonOatmeal,
  [bananaPeanutOatMash.slug]: bananaPeanutOatMash,
  [bananaTahiniToastStrips.slug]: bananaTahiniToastStrips,
  [beefTomatoPolentaMash.slug]: beefTomatoPolentaMash,
  [blackBeanMangoMash.slug]: blackBeanMangoMash,
  [blueberryPearFreezerCubes.slug]: blueberryPearFreezerCubes,
  [blueberryYogurtSwirl.slug]: blueberryYogurtSwirl,
  [carrotTahiniYogurtBlend.slug]: carrotTahiniYogurtBlend,
  [chickenBroccoliRiceBlend.slug]: chickenBroccoliRiceBlend,
  [chickpeaTomatoCuminBlend.slug]: chickpeaTomatoCuminBlend,
  [codPotatoLeekMash.slug]: codPotatoLeekMash,
  [cucumberYogurtDillSauce.slug]: cucumberYogurtDillSauce,
  [dateSweetenedOatmeal.slug]: dateSweetenedOatmeal,
  [edamameBroccoliBlend.slug]: edamameBroccoliBlend,
  [eggAvocadoToastStrips.slug]: eggAvocadoToastStrips,
  [eggSaladToastStrips.slug]: eggSaladToastStrips,
  [kefirBerrySmoothie.slug]: kefirBerrySmoothie,
  [kiwiOatmealStir.slug]: kiwiOatmealStir,
  [lambSquashKaleCubes.slug]: lambSquashKaleCubes,
  [lentilSweetPotatoCubes.slug]: lentilSweetPotatoCubes,
  [liverSweetPotatoBlend.slug]: liverSweetPotatoBlend,
  [mangoQuinoaBreakfastBowl.slug]: mangoQuinoaBreakfastBowl,
  [peachCottageCheeseWhip.slug]: peachCottageCheeseWhip,
  [peachRaspberryFreezerCubes.slug]: peachRaspberryFreezerCubes,
  [pearPruneMash.slug]: pearPruneMash,
  [porkAppleParsnipMash.slug]: porkAppleParsnipMash,
  [pumpkinPieYogurt.slug]: pumpkinPieYogurt,
  [quinoaVeggieCubes.slug]: quinoaVeggieCubes,
  [raspberryAmaranthPorridge.slug]: raspberryAmaranthPorridge,
  [redLentilTomatoCubes.slug]: redLentilTomatoCubes,
  [salmonAvocadoSmash.slug]: salmonAvocadoSmash,
  [sardineTomatoSmash.slug]: sardineTomatoSmash,
  [scrambledEggAvocadoMash.slug]: scrambledEggAvocadoMash,
  [shrimpPeaRiceBlend.slug]: shrimpPeaRiceBlend,
  [strawberryChiaJam.slug]: strawberryChiaJam,
  [strawberryFarinaPorridge.slug]: strawberryFarinaPorridge,
  [tofuRedPepperSmash.slug]: tofuRedPepperSmash,
  [turkeyTomatoCouscous.slug]: turkeyTomatoCouscous,
  [whiteBeanSpinachCubes.slug]: whiteBeanSpinachCubes,
};
